### ISSUE TITLE
TODO  List

### ISSUE THREAD

**Issue by Aimen06** [Aimen06/GameOn-website-FR#1]
1. [ ]  Corriger  la font du Header :  Roboto -> DM sans

2. En mode desktop : 

- [ ] Modifier l'image de la bannière  hero pour un format 16/9 
- [ ] Rendre responsive la page : menu, header, h1

3. En mode mobile : 

- [ ]  Faire apparaitre le bouton hamburger à la place du menu 
- [ ]  Le h1 doit tenir sur deux lignes (taille 41px) 
- [ ]  le paragraphe sous le titre doit avoir une taille de 13px

3. Formulaire :

- [ ]  Champ Prénom :  Faire un contrôle du champ et afficher l'erreur  dans  la span dessous
- [ ] Champ Nom :  Faire un contrôle du champ et afficher l'erreur  dans  la span dessous
- [ ] Champ Date :  Faire un contrôle du champ, afficher l'erreur  dans  la span dessous et limiter l'âge 13 ans.
- [ ]  Champ tournoi : Faire un contrôle du champ , afficher l'erreur  dans  la span dessous.
- [ ] Champ Lieu : Faire un contrôle du champ , afficher l'erreur  dans  la span dessous.
- [ ]  Décocher le champ des conditions (RGPD)
- [ ] Afficher la modal merci pour votre inscription après l'envoi du formuulaire
- [ ]  Fermer la modal en cliquant sur la  croix
